In [1]:
!pip install scikit-learn
import numpy as np

In [2]:
from sklearn.linear_model import LinearRegression
new_example = LinearRegression()

X = np.arange(30).reshape((10, 3))
y = range(10)
print(X)
print(y)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]
range(0, 10)


In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4)
print(X_train)

[[21 22 23]
 [27 28 29]
 [18 19 20]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  1  2]]


In [4]:
new_example.fit(X_train, y_train)
example_predictions = new_example.predict(X_test)
print(example_predictions)

[4. 5. 3. 8.]
